# Generated by Django 5.0.4 on 2024-04-14 12:02

import ckeditor_uploader.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.basemodel')),
                ('name_uz', models.CharField(max_length=15)),
                ('name_ru', models.CharField(max_length=15)),
                ('name_en', models.CharField(max_length=15)),
                ('short_description_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('short_description_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('short_description_en', models.CharField(blank=True, max_length=100, null=True)),
                ('long_description_uz', ckeditor_uploader.fields.RichTextUploadingField()),
                ('long_description_ru', ckeditor_uploader.fields.RichTextUploadingField()),
                ('long_description_en', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': 'About',
            },
            bases=('main.basemodel',),
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.basemodel')),
                ('name', models.CharField(max_length=255)),
                ('email_or_phone', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': 'contacts',
            },
            bases=('main.basemodel',),
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.basemodel')),
                ('name_uz', models.CharField(max_length=100)),
                ('name_ru', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='portfolio/images')),
                ('description_uz', ckeditor_uploader.fields.RichTextUploadingField()),
                ('description_ru', ckeditor_uploader.fields.RichTextUploadingField()),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField()),
                ('github', models.URLField(blank=True, null=True)),
                ('source', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=400, unique=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects',
            },
            bases=('main.basemodel',),
        ),
        migrations.CreateModel(
            name='SocialModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.basemodel')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('github', models.URLField()),
                ('linkedin', models.URLField()),
                ('facebook', models.URLField()),
                ('twitter', models.URLField()),
                ('instagram', models.URLField()),
                ('telegram', models.URLField()),
            ],
            options={
                'verbose_name': 'Social',
                'verbose_name_plural': 'Socials',
            },
            bases=('main.basemodel',),
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.basemodel')),
                ('name_uz', models.CharField(max_length=30)),
                ('name_ru', models.CharField(max_length=30)),
                ('name_en', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'tags',
            },
            bases=('main.basemodel',),
        ),
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.basemodel')),
                ('title_uz', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('description_uz', ckeditor_uploader.fields.RichTextUploadingField()),
                ('description_ru', ckeditor_uploader.fields.RichTextUploadingField()),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField()),
                ('image', models.ImageField(upload_to='blog/images')),
                ('slug', models.SlugField(blank=True, max_length=400, unique=True)),
                ('tags', models.ManyToManyField(blank=True, null=True, related_name='blogs', to='main.tagmodel')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'db_table': 'blogs',
            },
            bases=('main.basemodel',),
        ),
    ]
